config/routes.rb
Rails.application.routes.draw do
  resources :materia
  resources :resolutions
  resources :votos
  resources :alternativas
  resources :answers
  resources :questions
  resources :provas
  resources :simulados
  resources :ambitions
  resources :admission_exams
  resources :universidades
  resources :courses
  resources :universitarios
  resources :vestibulandos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admission_exam.rb
class AdmissionExam < ApplicationRecord
    has_and_belongs_to_many :universidades
    before_destroy {|admission_exam| admission_exam.universidades.clear}
    has_and_belongs_to_many :universitarios
    before_destroy {|admission_exam| admission_exam.universitarios.clear}
    has_many :ambitions, :dependent => :delete_all
    has_many :provas, :dependent => :delete_all

    def vestibular_info
        {
            admission_exam_id: self.id,
            name: self.name,
            desc: self.desc
        }
    end
end

app/models/alternativa.rb
class Alternativa < ApplicationRecord
    belongs_to :question
end

app/models/ambition.rb
class Ambition < ApplicationRecord
    VALID_FORMAT_REGEX = /\d{1}\.?\d{4}/
    validates :data, presence: true, length: { maximum: 6 }, format: { with: VALID_FORMAT_REGEX }

    belongs_to :course
    belongs_to :vestibulando
    belongs_to :admission_exam
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :simulado
    belongs_to :question
end

app/models/course.rb
class Course < ApplicationRecord
    extend Enumerize

    validates :name, presence: true
    enumerize :area, in: [:biological, :exact, :human], default: :exact

    has_and_belongs_to_many :universidades
    before_destroy {|course| course.universidades.clear}
    has_many :ambitions, :dependent => :delete_all
end

app/models/materium.rb
class Materium < ApplicationRecord
    has_and_belongs_to_many :questions, :dependent => :delete_all
    has_and_belongs_to_many :universitarios, :dependent => :delete_all
end

app/models/prova.rb
class Prova < ApplicationRecord
    belongs_to :admission_exam
    has_many :simulados
    before_destroy {|prova| prova.simulados.clear}
    has_many :questions, :dependent => :delete_all
end

app/models/question.rb
class Question < ApplicationRecord
    extend Enumerize
  
    validates :desc, presence: true, length: { minimum: 3 }
    validates :gabarito, presence: :true
    enumerize :type, in: [:alternativa, :dissertativa], default: :alternativa

    belongs_to :prova
    has_many :answers, :dependent => :delete_all
    has_many :alternativas, :dependent => :delete_all
    has_many :resolutions, :dependent => :delete_all
    has_and_belongs_to_many :materias
    before_destroy {|question| question.materias.clear}
end

app/models/resolution.rb
class Resolution < ApplicationRecord
    validates :desc, presence: true, length: { minimum: 6 }    

    belongs_to :question
    has_many :votos, :dependent => :delete_all
    belongs_to :universitario
end

app/models/simulado.rb
class Simulado < ApplicationRecord
    belongs_to :vestibulando
    belongs_to :prova 
    has_many :answers, :dependent => :delete_all
end

app/models/universidade.rb
class Universidade < ApplicationRecord
    validates :name, presence: true, length: { minimum: 6 }

    has_and_belongs_to_many :courses, :dependent => :delete_all
    before_destroy {|universidade| universidade.courses.clear}
    has_and_belongs_to_many :admission_exams, :dependent => :delete_all
    before_destroy {|universidade| universidade.admission_exams.clear}
end

app/models/universitario.rb
class Universitario < User
    type = "Universitario"
    has_and_belongs_to_many :admission_exams, :dependent => :delete_all
    before_destroy {|universitario| universitario.admission_exams.clear}
    has_and_belongs_to_many :materias, :dependent => :delete_all
    before_destroy {|universitario| universitario.materias.clear}
    has_many :resolutions, :dependent => :delete_all
    #def universitario_infos
    #    {
    #        username: self.username,
    #        email: self.email
    #        vestibulares: self.vestibulares_info(self.admission_exams)
    #    }
    #end

    #def vestibulares_info(admission_exam)
    #    admission_exam.map do |a|
    #        {
    #        admission_exam_id: a.id,
    #        admission_exam_name: a.name,
    #        admission_exam_selecionada: true
    #        }
    #    end
    #end
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
    include BCrypt
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    validates :email, presence: true, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
    validates :password_hash, presence: true
    validates :type, presence: true

    before_save :emailDownCase

    has_many :votos, :dependent => :delete_all
    
    def password
        @password ||= Password.new(password_hash)
    end
    
    def password=(new_password)
        @password = Password.create(new_password)
        self.password_hash = @password
    end

    def emailDownCase
        self.email = email.downcase
    end

    def functionTest
        true
    end
end

app/models/vestibulando.rb
class Vestibulando < User
    type = "Vestibulando"
    has_many :ambitions, :dependent => :delete_all
    has_many :simulados, :dependent => :delete_all

    def vestibulando_infos
        {
            username: self.username,
            email: self.email,
            vestibulares: self.vestibulares_info(self.ambitions)
        }
    end

    def vestibulares_info(ambitions)
        ambitions.map do |a|
            {
            admission_exam_id: a.admission_exam.id,
            admission_exam_name: a.admission_exam.name,
            admission_exam_selecionada: true
            }
        end
    end
end

app/models/voto.rb
class Voto < ActiveRecord::Base    
    belongs_to :user
    belongs_to :resolution
end

app/controllers/provas_controller.rb
class ProvasController < ApplicationController
  before_action :set_prova, only: [:show, :edit, :update, :destroy]

  # GET /provas
  # GET /provas.json
  def index
    @provas = Prova.all
  end

  # GET /provas/1
  # GET /provas/1.json
  def show
  end

  # GET /provas/new
  def new
    @prova = Prova.new
  end

  # GET /provas/1/edit
  def edit
  end

  # POST /provas
  # POST /provas.json
  def create
    @prova = Prova.new(prova_params)

    respond_to do |format|
      if @prova.save
        format.html { redirect_to @prova, notice: 'Prova was successfully created.' }
        format.json { render :show, status: :created, location: @prova }
      else
        format.html { render :new }
        format.json { render json: @prova.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provas/1
  # PATCH/PUT /provas/1.json
  def update
    respond_to do |format|
      if @prova.update(prova_params)
        format.html { redirect_to @prova, notice: 'Prova was successfully updated.' }
        format.json { render :show, status: :ok, location: @prova }
      else
        format.html { render :edit }
        format.json { render json: @prova.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provas/1
  # DELETE /provas/1.json
  def destroy
    @prova.destroy
    respond_to do |format|
      format.html { redirect_to provas_url, notice: 'Prova was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prova
      @prova = Prova.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prova_params
      params.require(:prova).permit(:name, :desc, :admission_exam_id)
    end
end

app/helpers/ambitions_helper.rb
module AmbitionsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/provas_helper.rb
module ProvasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votos_helper.rb
module VotosHelper
end

app/views/provas/_form.html.erb
<%= form_with(model: prova, local: true) do |form| %>
  <% if prova.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prova.errors.count, "error") %> prohibited this prova from being saved:</h2>

      <ul>
        <% prova.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="field">
    <%= form.label :admission_exam_id %>
    <%= form.text_field :admission_exam_id %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/provas/edit.html.erb
<h1>Editing Prova</h1>

<%= render 'form', prova: @prova %>

<%= link_to 'Show', @prova %> |
<%= link_to 'Back', provas_path %>

app/views/provas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Provas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Vestibular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provas.each do |prova| %>
      <tr>
        <td><%= prova.name %></td>
        <td><%= prova.desc %></td>
        <td><%= prova.admission_exam.name%></td>
        <td><%= link_to 'Show', prova %></td>
        <td><%= link_to 'Edit', edit_prova_path(prova) %></td>
        <td><%= link_to 'Destroy', prova, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prova', new_prova_path %>

app/views/provas/new.html.erb
<h1>New Prova</h1>

<%= render 'form', prova: @prova %>

<%= link_to 'Back', provas_path %>

app/views/provas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prova.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @prova.desc %>
</p>
<p>

<strong>Vestibular:</strong>
  <%= @prova.admission_exam.name %> |<%= link_to 'Show', @prova.admission_exam %>|
</p>

<p>
  <strong>Questões:</strong>
</p>
<%@prova.questions.map do |question|%>
<p><%=question.desc%> |<%= link_to 'Show', question %>|</p>
<%end%>

<p>
  <strong>Simulados:</strong>
</p>
<%@prova.simulados.map do |simulado|%>
<p><%=simulado.vestibulando.username%> fez em <%=simulado.created_at%> |<%= link_to 'Show', simulado %>|</p>
<%end%>



<%= link_to 'Edit', edit_prova_path(@prova) %> |
<%= link_to 'Back', provas_path %>