config/routes.rb
Rails.application.routes.draw do
  resources :materia
  resources :resolutions
  resources :votos
  resources :alternativas
  resources :answers
  resources :questions
  resources :provas
  resources :simulados
  resources :ambitions
  resources :admission_exams
  resources :universidades
  resources :courses
  resources :universitarios
  resources :vestibulandos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :simulado
    belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:desc, :correta, :question_id, :simulado_id)
    end
end

app/controllers/api/answers_controller.rb
class Api::AnswersController < ApplicationController
    skip_before_action :verify_authenticity_token

    def answer
        username = params[:username]
        password = params[:password]

        user = User.where("username": username).first
        
        return render json: {}, status: 400 if !user

        return render json: {}, status: 404 if user.password != password

        
        if user.type=="Vestibulando"
            return render json: user.vestibulando_infos.to_json 
        else    
            vestibulares = user.admission_exams
            render json: user.universitario_infos.to_json
        end
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>
  
  <div class="field">
    <%= form.label :correta %>
    <%= form.check_box :correta %>
  </div>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id %>
  </div>

  <div class="field">
    <%= form.label :simulado_id %>
    <%= form.text_field :simulado_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Respostas</h1>

<table>
  <thead>
    <tr>
      <th>Resposta</th>
      <th>Gabarito</th>
      <th>Correta</th>
      <th>Questão</th>
      <th>Prova</th>
      <th>Vestibulando</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.desc %></td>
        <td><%= answer.question.gabarito %></td>
        <td><%= answer.correta %></td>
        <td><%= answer.question.desc %></td>
        <td><%= answer.question.prova.name %> - <%= answer.question.prova.admission_exam.name %> </td>
        <td><%= answer.simulado.vestibulando.username %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resposta:</strong>
  <%= @answer.desc %>
</p>

<p>
  <strong>Gabarito:</strong>
  <%= @answer.question.gabarito %> 
</p>
<p>
  <strong>Correta:</strong>
  <%= @answer.correta %>
</p>

<p>
  <strong>Simulado:</strong>
  Feito em <%= @answer.simulado.created_at %> às <%= @answer.simulado.end %>  |<%= link_to 'Show',  @answer.simulado %>|
</p>
<p>
  <strong>Prova:</strong>
  <%= @answer.simulado.prova.name %> -  <%= @answer.simulado.prova.admission_exam.name %>  |<%= link_to 'Show',  @answer.simulado.prova %>|
</p>
<p>
  <strong>Questão:</strong>
  <%= @answer.question.desc %> |<%= link_to 'Show', @answer.question %>|
</p>



<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>