config/routes.rb
Rails.application.routes.draw do
  resources :materia
  resources :resolutions
  resources :votos
  resources :alternativas
  resources :answers
  resources :questions
  resources :provas
  resources :simulados
  resources :ambitions
  resources :admission_exams
  resources :universidades
  resources :courses
  resources :universitarios
  resources :vestibulandos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admission_exam.rb
class AdmissionExam < ApplicationRecord
    has_and_belongs_to_many :universidades
    before_destroy {|admission_exam| admission_exam.universidades.clear}
    has_and_belongs_to_many :universitarios
    before_destroy {|admission_exam| admission_exam.universitarios.clear}
    has_many :ambitions, :dependent => :delete_all
    has_many :provas, :dependent => :delete_all

    def vestibular_info
        {
            admission_exam_id: self.id,
            name: self.name,
            desc: self.desc
        }
    end
end

app/models/alternativa.rb
class Alternativa < ApplicationRecord
    belongs_to :question
end

app/models/ambition.rb
class Ambition < ApplicationRecord
    VALID_FORMAT_REGEX = /\d{1}\.?\d{4}/
    validates :data, presence: true, length: { maximum: 6 }, format: { with: VALID_FORMAT_REGEX }

    belongs_to :course
    belongs_to :vestibulando
    belongs_to :admission_exam
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :simulado
    belongs_to :question
end

app/models/course.rb
class Course < ApplicationRecord
    extend Enumerize

    validates :name, presence: true
    enumerize :area, in: [:biological, :exact, :human], default: :exact

    has_and_belongs_to_many :universidades
    before_destroy {|course| course.universidades.clear}
    has_many :ambitions, :dependent => :delete_all
end

app/models/materium.rb
class Materium < ApplicationRecord
    has_and_belongs_to_many :questions, :dependent => :delete_all
    has_and_belongs_to_many :universitarios, :dependent => :delete_all
end

app/models/prova.rb
class Prova < ApplicationRecord
    belongs_to :admission_exam
    has_many :simulados
    before_destroy {|prova| prova.simulados.clear}
    has_many :questions, :dependent => :delete_all
end

app/models/question.rb
class Question < ApplicationRecord
    extend Enumerize
  
    validates :desc, presence: true, length: { minimum: 3 }
    validates :gabarito, presence: :true
    enumerize :type, in: [:alternativa, :dissertativa], default: :alternativa

    belongs_to :prova
    has_many :answers, :dependent => :delete_all
    has_many :alternativas, :dependent => :delete_all
    has_many :resolutions, :dependent => :delete_all
    has_and_belongs_to_many :materias
    before_destroy {|question| question.materias.clear}
end

app/models/resolution.rb
class Resolution < ApplicationRecord
    validates :desc, presence: true, length: { minimum: 6 }    

    belongs_to :question
    has_many :votos, :dependent => :delete_all
    belongs_to :universitario
end

app/models/simulado.rb
class Simulado < ApplicationRecord
    belongs_to :vestibulando
    belongs_to :prova 
    has_many :answers, :dependent => :delete_all
end

app/models/universidade.rb
class Universidade < ApplicationRecord
    validates :name, presence: true, length: { minimum: 6 }

    has_and_belongs_to_many :courses, :dependent => :delete_all
    before_destroy {|universidade| universidade.courses.clear}
    has_and_belongs_to_many :admission_exams, :dependent => :delete_all
    before_destroy {|universidade| universidade.admission_exams.clear}
end

app/models/universitario.rb
class Universitario < User
    type = "Universitario"
    has_and_belongs_to_many :admission_exams, :dependent => :delete_all
    before_destroy {|universitario| universitario.admission_exams.clear}
    has_and_belongs_to_many :materias, :dependent => :delete_all
    before_destroy {|universitario| universitario.materias.clear}
    has_many :resolutions, :dependent => :delete_all
    #def universitario_infos
    #    {
    #        username: self.username,
    #        email: self.email
    #        vestibulares: self.vestibulares_info(self.admission_exams)
    #    }
    #end

    #def vestibulares_info(admission_exam)
    #    admission_exam.map do |a|
    #        {
    #        admission_exam_id: a.id,
    #        admission_exam_name: a.name,
    #        admission_exam_selecionada: true
    #        }
    #    end
    #end
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
    include BCrypt
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    validates :email, presence: true, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
    validates :password_hash, presence: true
    validates :type, presence: true

    before_save :emailDownCase

    has_many :votos, :dependent => :delete_all
    
    def password
        @password ||= Password.new(password_hash)
    end
    
    def password=(new_password)
        @password = Password.create(new_password)
        self.password_hash = @password
    end

    def emailDownCase
        self.email = email.downcase
    end

    def functionTest
        true
    end
end

app/models/vestibulando.rb
class Vestibulando < User
    type = "Vestibulando"
    has_many :ambitions, :dependent => :delete_all
    has_many :simulados, :dependent => :delete_all

    def vestibulando_infos
        {
            username: self.username,
            email: self.email,
            vestibulares: self.vestibulares_info(self.ambitions)
        }
    end

    def vestibulares_info(ambitions)
        ambitions.map do |a|
            {
            admission_exam_id: a.admission_exam.id,
            admission_exam_name: a.admission_exam.name,
            admission_exam_selecionada: true
            }
        end
    end
end

app/models/voto.rb
class Voto < ActiveRecord::Base    
    belongs_to :user
    belongs_to :resolution
end

app/controllers/ambitions_controller.rb
class AmbitionsController < ApplicationController
  before_action :set_ambition, only: [:show, :edit, :update, :destroy]

  # GET /ambitions
  # GET /ambitions.json
  def index
    @ambitions = Ambition.all
  end

  # GET /ambitions/1
  # GET /ambitions/1.json
  def show
  end

  # GET /ambitions/new
  def new
    @ambition = Ambition.new
  end

  # GET /ambitions/1/edit
  def edit
  end

  # POST /ambitions
  # POST /ambitions.json
  def create
    @ambition = Ambition.new(ambition_params)

    respond_to do |format|
      if @ambition.save
        format.html { redirect_to @ambition, notice: 'Ambition was successfully created.' }
        format.json { render :show, status: :created, location: @ambition }
      else
        format.html { render :new }
        format.json { render json: @ambition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ambitions/1
  # PATCH/PUT /ambitions/1.json
  def update
    respond_to do |format|
      if @ambition.update(ambition_params)
        format.html { redirect_to @ambition, notice: 'Ambition was successfully updated.' }
        format.json { render :show, status: :ok, location: @ambition }
      else
        format.html { render :edit }
        format.json { render json: @ambition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ambitions/1
  # DELETE /ambitions/1.json
  def destroy
    @ambition.destroy
    respond_to do |format|
      format.html { redirect_to ambitions_url, notice: 'Ambition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ambition
      @ambition = Ambition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ambition_params
      params.require(:ambition).permit(:data, :admission_exam_id, :vestibulando_id, :course_id)
    end
end

app/helpers/ambitions_helper.rb
module AmbitionsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/provas_helper.rb
module ProvasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votos_helper.rb
module VotosHelper
end

app/views/ambitions/_form.html.erb
<%= form_with(model: ambition, local: true) do |form| %>
  <% if ambition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ambition.errors.count, "error") %> prohibited this ambition from being saved:</h2>

      <ul>
        <% ambition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :admission_exam_id %>
    <%= form.text_field :admission_exam_id %>
  </div>

  <div class="field">
    <%= form.label :vestibulando_id %>
    <%= form.text_field :vestibulando_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ambitions/edit.html.erb
<h1>Editing Ambition</h1>

<%= render 'form', ambition: @ambition %>

<%= link_to 'Show', @ambition %> |
<%= link_to 'Back', ambitions_path %>

app/views/ambitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ambitions</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Curso</th>
      <th>Vestibular</th>
      <th>Vestibulando</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ambitions.each do |ambition| %>
      <tr>
        <td><%= ambition.data %></td>
        <td><%= ambition.course.name %></td>
        <td><%= ambition.admission_exam.name %></td>
        <td><%= ambition.vestibulando.username %></td>
        <td><%= link_to 'Show', ambition %></td>
        <td><%= link_to 'Edit', edit_ambition_path(ambition) %></td>
        <td><%= link_to 'Destroy', ambition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ambition', new_ambition_path %>

app/views/ambitions/new.html.erb
<h1>New Ambition</h1>

<%= render 'form', ambition: @ambition %>

<%= link_to 'Back', ambitions_path %>

app/views/ambitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @ambition.data %>
</p>
<p>
  <strong>Curso:</strong>
  <%= @ambition.course.name %>  |<%= link_to 'Show', @ambition.course %>|
</p>
<p>
  <strong>Vestibular:</strong>
  <%= @ambition.admission_exam.name %> |<%= link_to 'Show', @ambition.admission_exam %>|
</p>
<p>
  <strong>Vestibulando:</strong>
  <%= @ambition.vestibulando.username %> |<%= link_to 'Show', @ambition.vestibulando %>|
</p>

<%= link_to 'Edit', edit_ambition_path(@ambition) %> |
<%= link_to 'Back', ambitions_path %>